// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0JxIAtuXAMKvJrp-nOKsn67qP4vu19Mw',
    appId: '1:280688372552:web:95810c1576e45de02d617d',
    messagingSenderId: '280688372552',
    projectId: 'flutterfire-ui-codelab-6042a',
    authDomain: 'flutterfire-ui-codelab-6042a.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-6042a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhZsyyGJKKoSV6dUaqG9blJm_Dd52D6ho',
    appId: '1:280688372552:android:25726b757547a5322d617d',
    messagingSenderId: '280688372552',
    projectId: 'flutterfire-ui-codelab-6042a',
    storageBucket: 'flutterfire-ui-codelab-6042a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsap0QW0hoprsCBnTD_HAbMKfJIZwLJ8',
    appId: '1:280688372552:ios:56280b5275b151572d617d',
    messagingSenderId: '280688372552',
    projectId: 'flutterfire-ui-codelab-6042a',
    storageBucket: 'flutterfire-ui-codelab-6042a.appspot.com',
    iosClientId: '280688372552-qmi7g6ttp865c8jq1b0k2ubji2ppn0qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJsap0QW0hoprsCBnTD_HAbMKfJIZwLJ8',
    appId: '1:280688372552:ios:56280b5275b151572d617d',
    messagingSenderId: '280688372552',
    projectId: 'flutterfire-ui-codelab-6042a',
    storageBucket: 'flutterfire-ui-codelab-6042a.appspot.com',
    iosClientId: '280688372552-qmi7g6ttp865c8jq1b0k2ubji2ppn0qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
